sudo: true
language: Generic
os:
  - linux
  - linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - gfortran
    - gcc
    - mpich
    - liblapack-dev
    - liblapacke-dev
    - libmpich-dev
    - libopenblas-dev
    - mpich
install:
  - cd src/; make clean; make #2> makeLog

jobs:
  include:
    - name: v1
      os: linux
      script:
        - travis_wait 40 make test1 # already in src/ during install 
    - name: v2
      os: linux
      script:
        - travis_wait 40 make test2 # already in src/ during install 


